In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
#lab-2
#write a numpy program to implement following operations
#to convert a list of numeric array values into one-dimensional array



#Name:Arpita Makwana
#Enrollnment no:216270307069


import numpy as np
list=[1,2,3,4]
print("This is the original values",list)
list1=np.array(list)
print("This is the one-dimesional array",list)



This is the original values [1, 2, 3, 4]
This is the one-dimesional array [1, 2, 3, 4]


In [3]:
#lab-2
#write a numpy program to implement following operations
#o create a 3x3 matrix with values ranging from 2 to 10

#Name:Arpita Makwana
#Enrollnment no:216270307069

import numpy as np

#create a array
b = np.array([[10, 2, 3], [4, 5, 6], [7, 8, 9]])
print("b:\n", b)

b:
 [[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [4]:
#lab-2
#write a numpy program to implement following operations
# to append values at the end of an array


#Name:Arpita Makwana
#Enrollnment no:216270307069

import numpy as np

#create a simple array
a=np.array([1,2,3])
print("Before array",a)

#append the array
b=np.append(a,4)
print("After array",b)


Before array [1 2 3]
After array [1 2 3 4]


In [5]:
#lab-2
#write a numpy program to implement following operations
#to create another shape from an array without changing its data (3*2 to 2*3)

#Name:Arpita Makwana
#Enrollnment no:216270307069

import numpy as np
#create a 3*2 array
a=np.array([[1,2],[4,5],[7,8]])

#print the original array
print("original array",a)

#create a 2*3 array
b=a.reshape([2,3])

#print the reshaped array
print("Reshaped array",b)



original array [[1 2]
 [4 5]
 [7 8]]
Reshaped array [[1 2 4]
 [5 7 8]]
