In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:


#Name:Arpita Makwana
#Enrolment no: 216270307069

# Create a sample 2D array
original_array = np.array([[4, 2, 7],
                           [9, 5, 1],
                           [8, 6, 3]])

# Flatten the array in 'F' order
flattened_array = original_array.flatten(order='F')

# Find the maximum and minimum values in the flattened array
max_value = np.max(flattened_array)
min_value = np.min(flattened_array)

# Print the results
print("Flattened Array (in 'F' order):", flattened_array)
print("Maximum Value:", max_value)
print("Minimum Value:", min_value)


Flattened Array (in 'F' order): [4 9 8 2 5 6 7 1 3]
Maximum Value: 9
Minimum Value: 1


In [3]:
#to compute the mean, standard deviation, and variance of a given 
#array along the second axis

#Name:Arpita Makwana
#Enrollnment no:216270307069

#Mean
a = np.array([[1, 2], [3, 4]])
print("a:\n", a)
print("Mean of a along axis=1: ", np.mean(a, axis=1))

#standar Deviation
a = np.arange(12).reshape(3, 4)
print("a: \n", a)
print("Standard Deviation along axis=1: \n", np.std(a, axis=1))

#variance
a = np.random.randint(0, 12, (4, 3))
print("Variance along axis=1: \n", np.var(a, axis=1))



a:
 [[1 2]
 [3 4]]
Mean of a along axis=1:  [1.5 3.5]
a: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Standard Deviation along axis=1: 
 [1.11803399 1.11803399 1.11803399]
Variance along axis=1: 
 [16.22222222 14.88888889  9.55555556 22.22222222]


In [4]:
a = np.arange(12).reshape(3, 4)
print("a: \n", a)
print("Standard Deviation along axis=1: \n", np.std(a, axis=1))

a: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Standard Deviation along axis=1: 
 [1.11803399 1.11803399 1.11803399]


In [5]:
a = np.random.randint(0, 12, (4, 3))

print("Variance along axis=1: \n", np.var(a, axis=1))

Variance along axis=1: 
 [8.         4.22222222 6.22222222 8.22222222]
