In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:

# Write a NumPy program to implement following operation:
# 1.to add, subtract, multiply, divide arguments element-wise.

# Name:Arpita Makwana
#Enrolment no.216270307069

#This is the first method to implement add,sub,multiply,divide using operator
print("\nsimple method and using operator")
x = np.arange(5)
print("x =", x)
print("x + 5 =", x + 5)     #addication
print("x - 5 =", x - 5)     #subtracation
print("x * 2 =", x * 2)     #multiplication
print("x / 2 =", x / 2)      #division
print("x // 2 =", x // 2)    # floor division


#This is the second method to  implement add,sub,multiply,divide using universal function
print("\nuniversal method to implent above defination")
print("\nnp.add(3, 2):", np.add(3, 2))

x = np.arange(6)
print("\nx: \n", x)
print("\nnp.add(x, 2):\n", np.add(x, 2))                    # Addition +
print("\nnp.subtract(x, 5):\n", np.subtract(x, 5))          # Subtraction -
print("\n(np.negative(x):\n", np.negative(x))              # Unary negation -
print("\nnp.multiply(x, 3):\n", np.multiply(x, 3))          # Multiplication *
print("\nnp.divide(x, 2):\n", np.divide(x, 2))              # Division /
print("\nnp.floor_divide(x, 2):\n", np.floor_divide(x, 2))   # Floor division //



simple method and using operator
x = [0 1 2 3 4]
x + 5 = [5 6 7 8 9]
x - 5 = [-5 -4 -3 -2 -1]
x * 2 = [0 2 4 6 8]
x / 2 = [0.  0.5 1.  1.5 2. ]
x // 2 = [0 0 1 1 2]

universal method to implent above defination

np.add(3, 2): 5

x: 
 [0 1 2 3 4 5]

np.add(x, 2):
 [2 3 4 5 6 7]

np.subtract(x, 5):
 [-5 -4 -3 -2 -1  0]

(np.negative(x):
 [ 0 -1 -2 -3 -4 -5]

np.multiply(x, 3):
 [ 0  3  6  9 12 15]

np.divide(x, 2):
 [0.  0.5 1.  1.5 2.  2.5]

np.floor_divide(x, 2):
 [0 0 1 1 2 2]


In [3]:
#to round elements of the array to the nearest integer
# Name:Arpita Makwana
#Enrolment no: 216270307069

np.round([.5, 1.5, 2.5, 3.5, 4.6, 5.4, 6.5, 7.8])
np.around([.5, 1.5, 2.5, 3.5, 4.6, 5.4, 6.5, 7.8])           
np.rint([.5, 1.5, 2.5, 3.5, 4.6, 5.4, 6.5, 7.8]) 




array([0., 2., 2., 4., 5., 5., 6., 8.])

In [4]:
#to calculate mean across dimension, in a 2D numpy array

# Name:Arpita Makwana
#Enrolment no.216270307069

a = np.array([[3, 4], [4, 8]])
print("a:\n", a)
print("Mean of a: ", np.mean(a))
print("Mean of a along axis=0: ", np.mean(a, axis=0))
print("Mean of a along axis=1: ", np.mean(a, axis=1))

a:
 [[3 4]
 [4 8]]
Mean of a:  4.75
Mean of a along axis=0:  [3.5 6. ]
Mean of a along axis=1:  [3.5 6. ]


In [5]:
#to calculate the difference between neighboring elements, elementwise of a given array

# Name:Arpita Makwana
#Enrolment no.216270307069

x = np.array([[1, 3, 6, 10], [0, 5, 6, 8]])
print(np.diff(x),)

y=np.array([[4,8,9,11],[12,13,15,7]])

print(np.diff(y))

[[2 3 4]
 [5 1 2]]
[[ 4  1  2]
 [ 1  2 -8]]


In [6]:
x = np.array([1, 2, 4, 7, 0])
np.ediff1d(x)

array([ 1,  2,  3, -7])