In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
#Name:Makwana Arpita
#Enrollnment no:216270307069

import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
print("original array\n",a)
b=np.split(a,[2,6])
print("split array\n",b)

original array
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
split array
 [array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


In [3]:
#lab-2
#write a numpy program to implement following operations
#Write a NumPy program to implement following operation
# to stack arrays horizontally (column wise
#Name:Makwana Arpita
#Enrollnment no:216270307069

import numpy as np
x = np.arange(36, dtype=np.float32).reshape((6,6))
print("x: \n", x)
upper, lower = np.hsplit(x, [2])
print("\nUpper: \n", upper)
print("\nLower: \n", lower)
upper, middle, lower = np.vsplit(x, [2,3])
print("\nUpper: \n", upper)
print("\nMiddle: \n", middle)
print("\nLower: \n", lower) 

x: 
 [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]

Upper: 
 [[ 0.  1.]
 [ 6.  7.]
 [12. 13.]
 [18. 19.]
 [24. 25.]
 [30. 31.]]

Lower: 
 [[ 2.  3.  4.  5.]
 [ 8.  9. 10. 11.]
 [14. 15. 16. 17.]
 [20. 21. 22. 23.]
 [26. 27. 28. 29.]
 [32. 33. 34. 35.]]

Upper: 
 [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]

Middle: 
 [[12. 13. 14. 15. 16. 17.]]

Lower: 
 [[18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [4]:
#Name:Arpita Makwana
#Enrollnment no: 216270307069

import numpy as np

#array using arange
array = np.arange(25, dtype=np.float32).reshape((5,5))
print("Original Array  : \n", array)

# Horizontally spliting array into 2 parts
left, right = np.hsplit(array, [3])
print("\nLeft: \n", left)
print("\nRight: \n", right)

Original Array  : 
 [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]

Left: 
 [[ 0.  1.  2.]
 [ 5.  6.  7.]
 [10. 11. 12.]
 [15. 16. 17.]
 [20. 21. 22.]]

Right: 
 [[ 3.  4.]
 [ 8.  9.]
 [13. 14.]
 [18. 19.]
 [23. 24.]]
